// This is a minimal setup of a Forge mod workspace.
// For complex examples (including AccessTransformers, Jar-in-Jar, and Mixin), see our examples repository.
// https://github.com/MinecraftForge/MDKExamples

plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[7.0.3,8)'
    id 'net.minecraftforge.renamer' version '1.0.14'
}

version = mod_version
group = mod_group_id
base.archivesName = "${mod_id}-${minecraft_version}"

// Mojang ships Java 21 to end users in 1.20.5+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

// Include generated resources
sourceSets.main.resources { srcDir 'src/generated/resources' }

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            args "--mixin.config=${mod_id}.mixins.json"
        }

        register('client')

        register('server') {
            args '--nogui'
        }

        register('gameTestServer')

        register('data') {
            workingDir = layout.projectDirectory.dir('run-data')

            args '--mod', mod_id, '--all', '--output', layout.projectDirectory.dir('src/generated/resources'), '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }
}

renamer.enableMixinRefmaps {
    config "${mod_id}.mixins.json"
}
renamer.classes(tasks.named('jar', Jar)) {
    archiveClassifier = 'srg'
    // We need to use the generated mappings, which includes things generated by the annotation processor
    mappings renamer.mixin.generatedMappings
}

repositories {
    minecraft.mavenizer(it) // In Kotlin, it = this
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:1.21.11-61.2.0')
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.5'
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'
    implementation "com.github.glitchfiend:TerraBlender-forge:${minecraft_version}-${terra_blender_version}"
}
renamer.mappings(minecraft.dependency.toSrg)

tasks.named('processResources', ProcessResources) {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.property('replaceProperties', replaceProperties)

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}


tasks.named('jar', Jar) {
    manifest {
        attributes([
            'Specification-Title'     : mod_id,
            'Specification-Vendor'    : mod_authors,
            'Specification-Version'   : '1', // We are version 1 of ourselves
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : mod_authors
        ])
        attributes['MixinConfigs'] = "${mod_id}.mixins.json"
    }
}

idea.module { downloadJavadoc = downloadSources = true }

tasks.withType(JavaCompile).configureEach {
    // Use the UTF-8 charset for Java compilation
    // This is done by default in Java 18+, but this ensures it no matter the Java or Gradle version
    options.encoding = 'UTF-8'
}
