package womp.shellfishmod.blocks.animations;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class BlockAnimations {
    
    //Sea Lettuce
    public static final Animation NATURAL = Animation.Builder.create(7.958343f).looping()
		.addBoneAnimation("leaf20",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(-1.47f, 0f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf1",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0f, 0f, -0.03f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf2",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0f, 0f, -0.03f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf3",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(-1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(1.47f, 0f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf4",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(-1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(1.47f, 0f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf5",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(-1.5f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(1.5f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0.03f, 0f, 0.03f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf6",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-1.5f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(1.5f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(-1.47f, 0f, 1.47f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf7",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(-1.5f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(1.5f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0.03f, 0f, 0.03f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf8",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-1.5f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(1.5f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(-1.47f, 0f, 1.47f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf9",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(-1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(-0.03f, 0f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf10",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(-1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(-0.03f, 0f, 0f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf11",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0f, 0f, 1.47f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf12",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0f, 0f, 1.47f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf13",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(1.5f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(-1.5f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(-0.03f, 0f, 0.03f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf14",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(1.5f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(-1.5f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(1.47f, 0f, 1.47f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf15",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(1.5f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(-1.5f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(-0.03f, 0f, 0.03f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf16",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(1.5f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(-1.5f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(1.47f, 0f, 1.47f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf17",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0f, 0f, 0.03f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf18",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, -1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 1.5f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(0f, 0f, 0.03f),
					Transformation.Interpolations.LINEAR)))
		.addBoneAnimation("leaf19",
			new Transformation(Transformation.Targets.ROTATE,
				new Keyframe(0f, AnimationHelper.createRotationalVector(-1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(4f, AnimationHelper.createRotationalVector(1.5f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
					Transformation.Interpolations.LINEAR),
				new Keyframe(7.958343f, AnimationHelper.createRotationalVector(-1.47f, 0f, 0f),
					Transformation.Interpolations.LINEAR))).build();
}
