package womp.shellfishmod.blocks.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class BlockAnimations {
    
    //Sea Lettuce
    public static final AnimationDefinition NATURAL = AnimationDefinition.Builder.withLength(7.958343f).looping()
		.addAnimation("leaf20",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(-1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(-1.47f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf1",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(0f, 0f, -0.03f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf2",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(0f, 0f, -0.03f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf3",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(-1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(1.47f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf4",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(-1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(1.47f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf5",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(-1.5f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(1.5f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(0.03f, 0f, 0.03f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf6",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(-1.5f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(1.5f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(-1.47f, 0f, 1.47f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf7",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(-1.5f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(1.5f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(0.03f, 0f, 0.03f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf8",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(-1.5f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(1.5f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(-1.47f, 0f, 1.47f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf9",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(-1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(-0.03f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf10",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(-1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(-0.03f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf11",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(0f, 0f, 1.47f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf12",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(0f, 0f, 1.47f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf13",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(1.5f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(-1.5f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(-0.03f, 0f, 0.03f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf14",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(1.5f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(-1.5f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(1.47f, 0f, 1.47f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf15",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(1.5f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(-1.5f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(-0.03f, 0f, 0.03f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf16",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(1.5f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(-1.5f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(1.47f, 0f, 1.47f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf17",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0.03f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf18",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, -1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 1.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0.03f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("leaf19",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(-1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(4f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(7.958343f, KeyframeAnimations.degreeVec(-1.47f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR))).build();
}
